### ISSUE TITLE
No :main namespace specified in project.clj

### ISSUE THREAD

**Issue by practicalli-johnny** [mikeholmesuk/something-fun-cljs#1]
After cloning the project and running `lein run dev` from within the cloned folder, I get the error:

No :main namespace specified in project.clj.

Is this simply a missing :main declaration in the :dev profile ?

**Comment by mikeholmesuk** [comment]
Hi John,
Thanks for raising this. Let me take a look and I'll get back to you.
M

**Comment by mikeholmesuk** [comment]
Hi John,
The issue was an incorrect command noted by me in the README document. The command should be `lein dev` as opposed to `lein run dev` as originally stated. I've tested the new command and updated the doc. Would you please try the updated command at your earliest convenience and I'll close this if you confirm back that all is well.

**Comment by practicalli-johnny** [comment]
Yes, that works.  Thanks for the updated docs.
